var project = "my first console project";
console.log(project);
var first_name = "Davi";
console.log(first_name);
var last_name = "Duarte";
console.log(last_name);
var full_name = last_name.concat(first_name);
console.log(full_name);
var number1 = 4;
console.log(number1);
var number2 = 20;
console.log(number2);
var add = number2+number1;
console.log(add);
var subtract = number2-number1;
console.log(subtract);
var divide = number2/number1;
console.log(divide);
var multiply = number1*number2;
console.log(multiply);